export { default as IconCheck } from "./check.svg?react";
export { default as IconCopy } from "./copy.svg?react";
export { default as IconHome } from "./home.svg?react";
export { default as IconLogo } from "./logo.svg?react";
export { default as IconLogoWithText } from "./logo-with-text.svg?react";
export { default as IconPlus } from "./plus.svg?react";
export { default as IconRepeat } from "./repeat.svg?react";
export { default as IconSphere } from "./sphere.svg?react";
export { default as IconTrash } from "./trash.svg?react";
